#include "monstro_dados.h"
#include <stddef.h>

const MonstroInfo gMonstrosInfo[MONSTRO_TIPOS_COUNT] = {
    [MONSTRO_ESQUELETO] = {
        .tipo = MONSTRO_ESQUELETO,
        .nome = "Esqueleto",
        .sprites = {
            "assets/Monstros/esqueleto/esqueleto1.png",
            "assets/Monstros/esqueleto/esqueleto2.png",
            "assets/Monstros/esqueleto/esqueleto3.png",
        },
        .spriteObjeto = "assets/Monstros/esqueleto/pedra.png",
        .possuiObjeto = true,
        .vida = 85.0f,
        .velocidade = 240.0f,
        .fpsAnimacao = 8.0f,
        .alcanceAtaque = 230.0f,
        .cooldownAtaque = 1.2f,
        .danoContato = 10.0f,
        .danoObjeto = 10.0f,
        .velocidadeObjeto = 420.0f,
        .cooldownArremesso = 0.7f,
        .pontuacao = 25,
    },
    [MONSTRO_ZOMBIE] = {
        .tipo = MONSTRO_ZOMBIE,
        .nome = "Zumbi",
        .sprites = {
            "assets/Monstros/zombie/zombie1.png",
            "assets/Monstros/zombie/zombie2.png",
            "assets/Monstros/zombie/zombie3.png",
        },
        .possuiObjeto = false,
        .vida = 115.0f,
        .velocidade = 280.0f,
        .fpsAnimacao = 8.0f,
        .alcanceAtaque = 100.0f,
        .cooldownAtaque = 1.0f,
        .danoContato = 50.0f,
        .pontuacao = 40,
    },
    [MONSTRO_TIBBERS] = {
        .tipo = MONSTRO_TIBBERS,
        .nome = "Tibbers",
        .sprites = {
            "assets/Monstros/tibbers/Tibbers-1.png",
            "assets/Monstros/tibbers/Tibbers-2.png",
            "assets/Monstros/tibbers/Tibbers-3.png",
        },
        .possuiObjeto = false,
        .vida = 180.0f,
        .velocidade = 280.0f,
        .fpsAnimacao = 8.0f,
        .alcanceAtaque = 100.0f,
        .cooldownAtaque = 0.7f,
        .danoContato = 15.0f,
        .pontuacao = 60,
    },
    [MONSTRO_IT] = {
        .tipo = MONSTRO_IT,
        .nome = "IT",
        .sprites = {
            "assets/Monstros/IT/IT-1.png",
            "assets/Monstros/IT/IT-2.png",
            "assets/Monstros/IT/IT-3.png",
        },
        .spriteObjeto = "assets/Monstros/IT/balao.png",
        .possuiObjeto = true,
        .vida = 100.0f,
        .velocidade = 220.0f,
        .fpsAnimacao = 8.0f,
        .alcanceAtaque = 230.0f,
        .cooldownAtaque = 1.3f,
        .danoContato = 15.0f,
        .danoObjeto = 40.0f,
        .velocidadeObjeto = 220.0f,
        .cooldownArremesso = 1.6f,
        .pontuacao = 80,
    },
    [MONSTRO_CHUCKY] = {
        .tipo = MONSTRO_CHUCKY,
        .nome = "Chucky",
        .sprites = {
            "assets/Monstros/chucky/CHUCKY-1.png",
            "assets/Monstros/chucky/CHUCKY-2.png",
            "assets/Monstros/chucky/CHUCKY-3.png",
        },
        .possuiObjeto = false,
        .vida = 80.0f,
        .velocidade = 340.0f,
        .fpsAnimacao = 8.0f,
        .alcanceAtaque = 80.0f,
        .cooldownAtaque = 1.0f,
        .danoContato = 30.0f,
        .pontuacao = 25,
    },
    [MONSTRO_HEROBRINE] = {
        .tipo = MONSTRO_HEROBRINE,
        .nome = "Herobrine",
        .sprites = {
            "assets/Monstros/herobrine/herobrine-1.png",
            "assets/Monstros/herobrine/herobrine-2.png",
            "assets/Monstros/herobrine/herobrine-3.png",
        },
        .possuiObjeto = false,
        .vida = 240.0f,
        .velocidade = 280.0f,
        .fpsAnimacao = 8.0f,
        .alcanceAtaque = 100.0f,
        .cooldownAtaque = 1.3f,
        .danoContato = 70.0f,
        .pontuacao = 50,
    },
    [MONSTRO_RANDALL] = {
        .tipo = MONSTRO_RANDALL,
        .nome = "Randall",
        .sprites = {
            "assets/Monstros/randall/Randall-1.png",
            "assets/Monstros/randall/Randall-2.png",
            "assets/Monstros/randall/Randall-3.png",
        },
        .possuiObjeto = false,
        .vida = 70.0f,
        .velocidade = 390.0f,
        .fpsAnimacao = 8.0f,
        .alcanceAtaque = 80.0f,
        .cooldownAtaque = 0.6f,
        .danoContato = 15.0f,
        .pontuacao = 30,
    },
    [MONSTRO_SUPREMO] = {
        .tipo = MONSTRO_SUPREMO,
        .nome = "Supremo",
        .sprites = {
            "assets/Monstros/supremo/supremo-1.png",
            "assets/Monstros/supremo/supremo-2.png",
            "assets/Monstros/supremo/supremo-3.png",
        },
        .possuiObjeto = false,
        .vida = 300.0f,
        .velocidade = 235.0f,
        .fpsAnimacao = 8.0f,
        .alcanceAtaque = 100.0f,
        .cooldownAtaque = 1.8f,
        .danoContato = 100.0f,
        .pontuacao = 150,
    },
};

const MonstroInfo *ObterInfoMonstro(TipoMonstro tipo)
{
    if (tipo < 0 || tipo >= MONSTRO_TIPOS_COUNT) return NULL;
    return &gMonstrosInfo[tipo];
}
